services:
  app:
    image: eth_server
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - nebula-graphd

  nebula-metad:
    image: vesoft/nebula-metad:nightly
    container_name: nebula_metad
    environment:
      USER: root
    ports:
      - "9559:9559"
    volumes:
      - ./nebula/meta:/data/meta
    command:
      - --port=9559

  nebula-storaged:
    image: vesoft/nebula-storaged:nightly
    container_name: nebula_storaged
    environment:
      USER: root
    ports:
      - "9779:9779"
    volumes:
      - ./nebula/storage:/data/storage
    command:
      - --port=9779

  nebula-graphd:
    image: vesoft/nebula-graphd:nightly
    container_name: nebula-graphd
    environment:
      USER: root
    volumes:
      - ./nebula/graph:/data/graph
    ports:
      - "9669:9669"
    depends_on:
      - nebula-metad
      - nebula-storaged
    command: --meta_server_addrs=nebula-metad:9559